In [3]:
import numpy as np

In [33]:

'''
Given a array of numbers representing the stock prices of a company in chronological order, write a function that calculates the maximum profit you could have made from buying and selling that stock. You're also given a number fee that represents a transaction fee for each buy and sell transaction.

You must buy before you can sell the stock, but you can make as many transactions as you like.

For example, given [1, 3, 2, 8, 4, 10] and fee = 2, you should return 9, since you could buy the stock at 1 dollar, and sell at 8 dollars, and then buy it at 4 dollars and sell it at 10 dollars. Since we did two transactions, there is a 4 dollar fee, so we have 7 + 6 = 13 profit minus 4 dollars of fees.
'''

stocks=[1, 3, 2, 8, 4, 10]

fee=2

#Construct a directed graph that encodes the problem. 

def construct_graph(stocks,fee):
    adj_mat=np.zeros((len(stocks),len(stocks)))
    for j in range(len(stocks)):
        #roll_arr=[0]*len(stocks)+stocks+[0]*len(stocks)
        #roll_arr=np.roll(roll_arr,shift=j)
        adj_mat[j,j:]=stocks[j:]
    return adj_mat

adj_mat=construct_graph(stocks,fee)
print(adj_mat)


[[ 1.  3.  2.  8.  4. 10.]
 [ 0.  3.  2.  8.  4. 10.]
 [ 0.  0.  2.  8.  4. 10.]
 [ 0.  0.  0.  8.  4. 10.]
 [ 0.  0.  0.  0.  4. 10.]
 [ 0.  0.  0.  0.  0. 10.]]
